---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

# https://rubocop.readthedocs.io/en/latest/
AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 500

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'test/**/*'

Layout/LineLength:
  Max: 200

Style/NumericPredicate:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/redis-cluster-client.rb'
